server:
  port: 8082
  servlet.context-path: /api
logging:
  level:
    root: info
    com.lrm: debug
  file.name: logs/my.log


book:
  name: 互聯網世界觀
  author: 李善有
  isbn: ${random.uuid}
  description: ${book.name} ,好書